[versions]
kotlin = "2.1.20"
mcp = "0.4.0"
spock = "2.3-groovy-3.0"

[libraries]
mcp-sdk = { group = "io.modelcontextprotocol", name = "kotlin-sdk", version.ref = "mcp" }
spock-core = { group = "org.spockframework", name = "spock-core", version.ref = "spock" }

[plugins]
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version = "2.1.20" }
kotlin-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
